### ISSUE TITLE
schematic

### ISSUE THREAD

**Issue by iddq** [bit2shift/serprog-due#1]
Can you please share the wiring diagram/details? Thank you.

**Comment by bit2shift** [comment]
Can you be a little more specific about your request?

**Comment by iddq** [comment]
How could I connect SPI flash to due?

**Comment by bit2shift** [comment]
If it's on a motherboard like in the images below, then you need a SOP8 test clip. You can find them online with the ribbon cable pre-assembled.

For the specific flash chip pinout, you need to consult the respective datasheet.
If using the Arduino Due, you need some male-female jumper cables or an ICSP cable.
The default _chip select_ pin (CS) is the 52nd.

Once you have all the necessary parts, you can take a look at the first lines of [`serprog-due.ino`](https://github.com/bit2shift/serprog-due/blob/master/serprog-due/serprog-due.ino) to see how I connected things up in the scenario of the 2nd image from below (laptop motherboard).
<details>
<summary>Clip on motherboard</summary>
<img src="https://raw.githubusercontent.com/bit2shift/serprog-due/master/clip.jpg"/>
<img src="https://raw.githubusercontent.com/bit2shift/serprog-due/master/overview.jpg"/>
</details>
<details>
<summary>ICSP pinout, cable and example assemblage</summary>
<img src="https://www.arduinolab.net/wp-content/uploads/2017/05/ArduinoUnoR3ISPconnector.jpg"/>
<img src="http://www.gammon.com.au/images/Arduino/Chip_Programmer7.jpg"/>
<img src="https://static.efetividade.net/img/attiny-2015-05-02-17.44.08-15524.jpeg"/>
</details>

**Comment by iddq** [comment]
I see, so the data/clock pins are on the ICSP connector.

SPI Flash - Due
---------------

CS# - 52 SPI-CS2
MISO - ICSP header pin 1, MISO2
MOSI - ICSP header pin 4, MOSI2
SCLK - ICSP header pin 3, SCLK2

**Comment by iddq** [comment]
Do you know what does mean two at the end of the names?  Does due have MISO1?

**Comment by bit2shift** [comment]
Yes, but keep in mind that the VCC pin on that header is 5 V, not 3,3 V.
<img src="http://www.robgray.com/temp/Due-pinout-A4.png"/>

**Comment by iddq** [comment]
Just to be clear do you use the ICSP socket or the SPI socket on the board?

**Comment by bit2shift** [comment]
The SPI header of the Due is the same (location- and function-wise) as the ICSP header of regular Arduino boards.

---
The SAM3X8E doesn't have ICSP like AVR chips do, so the header is provided on the board for compatibility with shields.

---
Please ignore the ICSP header next to the ATmega16U2 chip that provides the standard serial port.

**Comment by iddq** [comment]
Thank you
